### PR TITLE
adds cancellation token support

### LINKED ISSUE #42: CancellationToken support
Hey there!

## Problem statement 

I started playing with this library a bit more in depth and one of the things missing for me is `CancellationToken` support.  The reason passing down a CancellationToken so database connections don't stay open longer than they need for.  

For example, a user could create a complex search, start the query, then decide to do something else, and move away from the page.  Without passing along the `CancellationToken` to the database query, it may run in the background for some time, consuming resources.

## Changes

I'll be sending a Pull Request shortly with the proposed changes.

### PR DESCRIPTION
**Pull request by TheAngryByrd**
Closes #42 

--- 

I haven't added tests just yet but I wanted to show the proposed changes.  Let me know what kind of tests you think would be appropriate for this PR.

Since these are optional parameters it shouldn't be a breaking change.

### CODE REVIEW

**Comment by pimbrouwers** [comment]
First off, thanks for doing this Jimmy. Truly do appreciate it. 

Had a check of the code, it looks great.

As for tests, and correct me if I am wrong, should only be to verify that it is being passed into the proper classes. Since the library is really just shuttling it through and the handling of it is entirely on the consumer. Thoughts?

**Comment by TheAngryByrd** [comment]
Ok added tests for the main entry points for the:

## `DB.Async` module 
* [exec](https://github.com/pimbrouwers/Donald/pull/43/files#diff-e508fd23ecce459eba2f10be31fd71ebeb48cb82809d5dcac140d6c1e6b11937R549-R573)
* [execMany](https://github.com/pimbrouwers/Donald/pull/43/files#diff-e508fd23ecce459eba2f10be31fd71ebeb48cb82809d5dcac140d6c1e6b11937R576-R593)
* [scalar](https://github.com/pimbrouwers/Donald/pull/43/files#diff-e508fd23ecce459eba2f10be31fd71ebeb48cb82809d5dcac140d6c1e6b11937R462-R475)
* [query](https://github.com/pimbrouwers/Donald/pull/43/files#diff-e508fd23ecce459eba2f10be31fd71ebeb48cb82809d5dcac140d6c1e6b11937R503-R524)
* [querySingle](https://github.com/pimbrouwers/Donald/pull/43/files#diff-e508fd23ecce459eba2f10be31fd71ebeb48cb82809d5dcac140d6c1e6b11937R478-R499)
* [read](https://github.com/pimbrouwers/Donald/pull/43/files#diff-e508fd23ecce459eba2f10be31fd71ebeb48cb82809d5dcac140d6c1e6b11937R527-R546)

## `Builder`

- [cmdCancel](https://github.com/pimbrouwers/Donald/pull/43/files#diff-e508fd23ecce459eba2f10be31fd71ebeb48cb82809d5dcac140d6c1e6b11937R629-R632)

## Extensions

Left to do:
- [ ] TryOpenConnectionAsync
- [ ] TryBeginTransactionAsync
- [ ] TryRollbackAsync
- [ ] TryCommitAsync

**Comment by pimbrouwers** [comment]
Amazing, thank you. You think there is value in directly testing the extensions module? I just figured it was sufficient to test the consumers.

**Comment by TheAngryByrd** [comment]
> Amazing, thank you. You think there is value in directly testing the extensions module? I just figured it was sufficient to test the consumers.

Probably not `TryOpenConnectionAsync` as it's in `tryDo` path but the others aren't tested in the happy path or the cancel path.  It's probably not a big deal to not test them as they're small but I'll really leave that decision up to you.

**Comment by pimbrouwers** [comment]
Ultimately how I saw it as well. But never hurts to get the opinion of someone harder, better, faster, stronger 😝.

**Pull request merged**
