### PR TITLE
CLR exceptions

### PR DESCRIPTION
**Pull request by pimbrouwers**
- Removes `Result` from execution pipeline.
- Introduces `SqlType` help functions.

### CODE REVIEW

**Comment by sbacquet** [comment]
This is a major breaking change.
What is the rational behind ?

**Comment by pimbrouwers** [comment]
Indeed, which is why it was a major package number bump.

Was an experienced-based decision based on writing hundreds of programs,
noticing that there was hardly a salient use case for handling errors
monadically. If the DB execution fails, what are you reasonably going to do
other than log/report the error?

**Comment by sbacquet** [comment]
> Indeed, which is why it was a major package number bump.

Ok, but I guess branch 9.x will not be maintained ;)

> there was hardly a salient use case for handling errors monadically

Are you talking about DB execution specifically, or in general ?

> If the DB execution fails, what are you reasonably going to do other than log/report the error?

DB execution is just a step in monadic pipelines.
Throwing exceptions is not idiomatic and breaks the pipeline.
To me, returning `Result<'T, System.Exception>` is the best way to manage errors in .NET.

Anyway for Donald it's not a big deal : I'll surround the calls to `Db.exec` and `Db.Async.exec` with `try/with` and return `Error exception`.

**Comment by pimbrouwers** [comment]
I never said that. I am more than happy to patch version 9.x if issues come
up. Is there a specific issue you've been facing?

My last response was specifically about database execution, there is
clearly a very well demonstrated use for monadic error handling.

I wouldn't say this change prevents you from using this in pipelines at
all. The library produces a limited number of exceptions, so creating an
adapter function should be quite simple. I considered including it, but
after some discussion with a few other devs, opted against it. Happy to
consider that as well, if that would suit you?

I apologize for the inconvenience.

**Comment by sbacquet** [comment]
Donald is working like a charm, thanks for publishing this nice library :)
I'll adapt my code to version 10, no worries.

**Comment by pimbrouwers** [comment]
My pleasure. Very glad you like it! I do as well!

**Comment by sbacquet** [comment]
Hello - sorry to bother you
I'm migrating my code to version 10 with CLR exceptions.
The exceptions that I'm catching are of type : AggregateException -> Inner = Donald.DbExecutionException -> Inner = OracleException
That's a lot of layers. Do you know why an AggregateException is thrown and how to avoid it ?
Thanks !

**Comment by sbacquet** [comment]
I've ended up with the following adapter :
```
let rec donaldExToError (ex:Exception) =
    match ex with
    | :? Donald.DbConnectionException as ex ->
        Error ex.InnerException
    | :? Donald.DbExecutionException as ex ->
        Error ex.InnerException
    | :? Donald.DbTransactionException as ex ->
        Error ex.InnerException
    | :? Donald.DbReaderException as ex ->
        Error ex.InnerException
    | :? AggregateException as ex ->
        donaldExToError ex.InnerException
    | ex ->
        Error ex // should never happen
```

**Pull request merged**
